/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * 非活性にするフィールドの設定
   */
  disabledFields: {
    /**
     * フィールドコード
     */
    fieldCode: string;
    /**
     * フィールドを非活性にするかどうか
     */
    disabled: boolean;
    condition?: {
      /**
       * 比較タイプ
       */
      compareType: "field" | "value";
      /**
       * 比較対象のフィールド
       */
      field: string;
      /**
       * 比較演算子
       */
      operator: "=" | "!=" | ">" | "<" | ">=" | "<=";
      /**
       * 比較対象の値
       */
      value: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
}
